#include "ucl.h"
#include "ast.h"
#include "decl.h"
#include "output.h"
#include "target.h"
int SwitchTableNum;
/**
 * Emit all the strings to assembly file
 */
static void EmitGlobals(void)
{
	Symbol p = Globals;
	while (p)
	{
		DefineCommData(p);
		p = p->next;
	}
	PutString("\n");
}
static void EmitStrings(void)
{
	Symbol p = Strings;
	String str;
	int len;
	int size;
	while (p)
	{
		DefineGlobal(p);
		str = (String)p->val.p;
		//printf("%s\n", str->chs);
		//assert(p->ty->categ == ARRAY);
		size = str->len + 1;
		DefineString(str, size);
		p = p->next;
	}
	PutString("\n");
}

/**
 * Emit all the functions
 */
static void EmitFunctions(AstTranslationUnit transUnit)
{
	AstNode p;
	FunctionSymbol fsym;
	p = transUnit->extDecls;
	while (p != NULL)
	{
		
		if (p->kind == NK_Function)
		{
			fsym = ((AstFunction)p)->fsym;
			EmitFunction(fsym);
		}
		p = p->next;
	}
}

/**
 * Emit  assembly code for the translation unit
 */
void EmitTranslationUnit(AstTranslationUnit transUnit)
{
	if(ASMFileName){
		ASMFile = fopen(ASMFileName, "w");
		ASMFileName = NULL;
	}else{
		ASMFile = CreateOutput(Input.filename, ExtName);
	}
	SwitchTableNum = 1;
	// "# Code auto-generated by UCC\n\n"
	BeginProgram();
	// ".data\n\n"
	Segment(DATA);
	/**
		.str0:	.string	"%d \012"
		.str1:	.string	"a + b + c + d = %d.\012"
	 */
	EmitStrings();
	
	EmitGlobals();
	// ".text\n\n"
	Segment(CODE);

	/**
		The key function is 
			void EmitFunction(FunctionSymbol fsym)
		in x86.c
	 */
	EmitFunctions(transUnit);

	EndProgram();

	fclose(ASMFile);
}
