#ifndef OPCODE
#error "You must define OPCODE macro before include this file"
#endif
/**
	opcode here is used by UIL
 */
OPCODE(BOR,     "|",                    Assign)
OPCODE(BXOR,    "^",                    Assign)
OPCODE(BAND,    "&",                    Assign) 
OPCODE(LSH,     "<<",                   Assign)
OPCODE(RSH,     ">>",                   Assign)
OPCODE(ADD,     "+",                    Assign)
OPCODE(SUB,     "-",                    Assign)
OPCODE(MUL,     "*",                    Assign)
OPCODE(DIV,     "/",                    Assign)
OPCODE(MOD,     "%",                    Assign)
OPCODE(NEG,		"-",					Assign)
OPCODE(BCOM,	"~",					Assign)
OPCODE(JZ,      "",                     Branch)
OPCODE(JNZ,     "!",                    Branch)
OPCODE(JE,      "==",                   Branch)
OPCODE(JNE,     "!=",                   Branch)
OPCODE(JG,      ">",                    Branch)
OPCODE(JL,      "<",                    Branch)
OPCODE(JGE,     ">=",                   Branch)
OPCODE(JLE,     "<=",                   Branch)
OPCODE(MOV,     "=",                    Move)
OPCODE(IMOV,    "*=", 					IndirectMove)
OPCODE(RET, 	"ret", 					Return)
OPCODE(JMP, 	"jmp",					Jump)
OPCODE(IJMP, 	"jmp",					IndirectJump)
OPCODE(CALL,    "call",                 Call)
OPCODE(ADDR,    "&",                    Address)
OPCODE(DEREF,	"*",					Deref)
OPCODE(EXTI1,	"(int)(char)",			Cast)
OPCODE(EXTI2,	"(int)(short)",			Cast)
OPCODE(TRUI1,   "(char)(int)",          Cast)
OPCODE(CLR,		"",						Clear)
OPCODE(NOP, 	"NOP",					NOP)
