#ifndef TOKENOP
#error "You must define TOKENOP macro before include this file"
#endif
//      Token               binary op       unary op
TOKENOP(TK_ASSIGN,        OP_ASSIGN,        OP_NONE)
TOKENOP(TK_BITOR_ASSIGN,  OP_BITOR_ASSIGN,  OP_NONE)
TOKENOP(TK_BITXOR_ASSIGN, OP_BITXOR_ASSIGN, OP_NONE)
TOKENOP(TK_BITAND_ASSIGN, OP_BITAND_ASSIGN, OP_NONE)
TOKENOP(TK_LSHIFT_ASSIGN, OP_LSHIFT_ASSIGN, OP_NONE)
TOKENOP(TK_RSHIFT_ASSIGN, OP_RSHIFT_ASSIGN, OP_NONE)
TOKENOP(TK_ADD_ASSIGN,    OP_ADD_ASSIGN,    OP_NONE)
TOKENOP(TK_SUB_ASSIGN,    OP_SUB_ASSIGN,    OP_NONE)
TOKENOP(TK_MUL_ASSIGN,    OP_MUL_ASSIGN,    OP_NONE)
TOKENOP(TK_DIV_ASSIGN,    OP_DIV_ASSIGN,    OP_NONE)
TOKENOP(TK_MOD_ASSIGN,    OP_MOD_ASSIGN,    OP_NONE)

TOKENOP(TK_OR,            OP_OR,            OP_NONE)
TOKENOP(TK_AND,           OP_AND,           OP_NONE)
TOKENOP(TK_BITOR,         OP_BITOR,         OP_NONE)
TOKENOP(TK_BITXOR,        OP_BITXOR,        OP_NONE)
TOKENOP(TK_BITAND,        OP_BITAND,        OP_NONE)
TOKENOP(TK_LSHIFT,        OP_LSHIFT,        OP_NONE)
TOKENOP(TK_RSHIFT,        OP_RSHIFT,        OP_NONE)
TOKENOP(TK_ADD,           OP_ADD,           OP_NONE)
TOKENOP(TK_SUB,           OP_SUB,           OP_NONE)
TOKENOP(TK_MUL,           OP_MUL,           OP_NONE)
TOKENOP(TK_DIV,           OP_DIV,           OP_NONE)
TOKENOP(TK_MOD,           OP_MOD,           OP_NONE)
