# Code auto-generated by UCC

.data

.str0:	.string	"hello world"

.text

.globl	main

main:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $4, %esp
.BB0:
	leal .str0, %eax
	pushl %eax
	call puts
	addl $4, %esp
.BB1:
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

