# Code auto-generated by UCC

.data

.str0:	.string	"hello world"

.comm	a,4
.comm	b,4

.text

.globl	printf_hw

printf_hw:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $8, %esp
.BB0:
	leal .str0, %eax
	pushl %eax
	call puts
	addl $4, %esp
	jmp .BB2
.BB1:
.BB2:
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

.globl	main

main:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $4, %esp
.BB3:
	pushl $2
	pushl $1
	call printf_hw
	addl $8, %esp
	movl $1, %eax
	jmp .BB5
.BB4:
.BB5:
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

