# Code auto-generated by UCC

.data

.str0:	.string	"Hw"


.text

.globl	print_hw

print_hw:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $4, %esp
.BB0:
	leal .str0, %eax
	pushl %eax
	call puts
	addl $4, %esp
	movl $48, %eax
	jmp .BB2
.BB1:
.BB2:
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

.globl	main

main:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $4, %esp
.BB3:
	call print_hw
	movl $1, %eax
	jmp .BB5
.BB4:
.BB5:
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

